---
- name: Gitolite .rc dosyasi duzenleniyor.
  replace:
     dest: "{{ item.value.dest }}"
     regexp: "{{ item.value.regexp }}"
     replace: "{{ item.value.replace }}"
  with_dict: "{{gitolite_rc}}"
  sudo: "yes"
  sudo_user: "gitolite"
  tags: hook

- name: MYS ve GDYS hook dizinleri olusturuluyor.
  file:
     path: "{{ hook_directory['path'] }}"
     owner: "{{ hook_directory['owner'] }}"
     group: "{{ hook_directory['group'] }}"
     mode: "{{ hook_directory['mode'] }}"
     state: "{{ hook_directory['state'] }}"
  notify: Gitolite-Admin repo degisiklikleri uygulaniyor.
  sudo: "yes"
  sudo_user: "gitolite"
  tags: hook

- name: MYS ve GDYS hook scriptleri olusturuluyor.
  template:
     src: "{{ item.value.src }}"
     dest: "{{ item.value.dest }}"
     owner: "{{ item.value.owner }}"
     group: "{{ item.value.group }}"
     mode: "{{ item.value.mode }}"
  with_dict: "{{hook_scripts}}"
  notify: Gitolite-Admin repo degisiklikleri uygulaniyor.
  become: true
  become_user: root
  register: result
  tags: hook

- name: MYS ve GDYS hook anahtarlari olusturuluyor.
  command: "/usr/bin/ssh-keygen -t rsa -f {{ item.value.name }} -N ''"
  with_dict: "{{hook_keys}}"
  sudo: "yes"
  sudo_user: "gitolite"
  when: result.changed
  tags: repokeys

- name: MYS ve GDYS hook anahtarlari authorized_keys'e ekleniyor.
  shell: "/usr/bin/paste <(/bin/echo {{ item.value.option }}) {{ item.value.name }}.pub -d ' ' >> /home/ahtapotops/.ssh/authorized_keys"
  args:
     executable: "/bin/bash"
  with_dict: "{{hook_keys}}"  
  sudo: "yes"
  when: result.changed
  tags: repokeys
